### ISSUE TITLE
Make links appear in the usual styling in the plainhtml version

### ISSUE THREAD

**Issue by koljapluemer** [koljapluemer/inspirationbot#9]
In the [Plain HTML version](https://inspirationbot.art/versions/plainhtml/main.html) links are currently not styled in the correct fashion one would expect in HTML (underline, blue), because their target is empty.

Find a way to fix this; either with CSS or by setting a target that does not break the functionality of the site.

**Comment by Sookeyy-12** [comment]
can i work on this issue?

**Comment by koljapluemer** [comment]
Absolutely! Good luck and feel free to ask if you're stuck.
